
#include <eigen3/Eigen/Dense>
#include <fstream>
#include <sstream>
#include <cmath>
#include <iostream>
#include <boost/function.hpp>
#include <boost/bind.hpp>
#include "ros/ros.h"
#include <tf/transform_listener.h>
#include "std_msgs/Float64.h"
#include "std_msgs/Float64MultiArray.h"
#include "sensor_msgs/JointState.h"
#include "gazebo_msgs/LinkStates.h"
#include "geometry_msgs/Wrench.h"
#include <geometry_msgs/WrenchStamped.h>
#include <rosbag/bag.h>
#include <rosbag/view.h>
#include <string>
#include <signal.h> 
#include <sensor_msgs/Imu.h>
#include <std_msgs/String.h>
#include <std_msgs/Bool.h>
#include <std_msgs/UInt8.h>
#include <vector>
#include <algorithm>
#include <std_msgs/Float32.h>
#include <deque>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Twist.h>
